---

- name: Prepare systems for k8s
  hosts: all
  roles:
    - role: prepareOS
      become: yes

- name: Prepare control plane
  hosts: k8s_master
  roles:
    - role: prepareCP
      become: yes

- name: Install nfs_server
  hosts: k8s_master
  roles:
    - role: nfs_server
      become: yes
